"""autogenerated by genpy from my_dynamixel_tutorial/angles.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class angles(genpy.Message):
  _md5sum = "01c16b8753716d52de66552164fe680a"
  _type = "my_dynamixel_tutorial/angles"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 theta1
float64 theta2
float64 theta3
float64 theta4
float64 theta5
float64 theta6

"""
  __slots__ = ['theta1','theta2','theta3','theta4','theta5','theta6']
  _slot_types = ['float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       theta1,theta2,theta3,theta4,theta5,theta6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(angles, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.theta1 is None:
        self.theta1 = 0.
      if self.theta2 is None:
        self.theta2 = 0.
      if self.theta3 is None:
        self.theta3 = 0.
      if self.theta4 is None:
        self.theta4 = 0.
      if self.theta5 is None:
        self.theta5 = 0.
      if self.theta6 is None:
        self.theta6 = 0.
    else:
      self.theta1 = 0.
      self.theta2 = 0.
      self.theta3 = 0.
      self.theta4 = 0.
      self.theta5 = 0.
      self.theta6 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.theta1, _x.theta2, _x.theta3, _x.theta4, _x.theta5, _x.theta6))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.theta1, _x.theta2, _x.theta3, _x.theta4, _x.theta5, _x.theta6,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.theta1, _x.theta2, _x.theta3, _x.theta4, _x.theta5, _x.theta6))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.theta1, _x.theta2, _x.theta3, _x.theta4, _x.theta5, _x.theta6,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
