/* Auto-generated by genmsg_cpp for file /home/ssr/fuerte_workspace/sandbox/my_dynamixel_tutorial/msg/xyz.msg */
#ifndef MY_DYNAMIXEL_TUTORIAL_MESSAGE_XYZ_H
#define MY_DYNAMIXEL_TUTORIAL_MESSAGE_XYZ_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace my_dynamixel_tutorial
{
template <class ContainerAllocator>
struct xyz_ {
  typedef xyz_<ContainerAllocator> Type;

  xyz_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  xyz_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;


  typedef boost::shared_ptr< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_dynamixel_tutorial::xyz_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct xyz
typedef  ::my_dynamixel_tutorial::xyz_<std::allocator<void> > xyz;

typedef boost::shared_ptr< ::my_dynamixel_tutorial::xyz> xyzPtr;
typedef boost::shared_ptr< ::my_dynamixel_tutorial::xyz const> xyzConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::my_dynamixel_tutorial::xyz_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace my_dynamixel_tutorial

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_dynamixel_tutorial::xyz_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const  ::my_dynamixel_tutorial::xyz_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_dynamixel_tutorial/xyz";
  }

  static const char* value(const  ::my_dynamixel_tutorial::xyz_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::my_dynamixel_tutorial::xyz_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct xyz_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_dynamixel_tutorial::xyz_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::my_dynamixel_tutorial::xyz_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MY_DYNAMIXEL_TUTORIAL_MESSAGE_XYZ_H

